apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx:1.20.1-alpine
          name: nginx 
          environment:
            - name: NGINX_PORT
              value: '8000'
          ports:
            - name: http   
              containerPort: '8000'
